### ISSUE TITLE
Unnecessary arguments check in plugin?

### ISSUE THREAD

**Issue by manast** [Daplie/le-store-SPEC#3]
Why are these checks needed in the plugin?
https://github.com/Daplie/le-store-SPEC/blob/master/index.js#L27-L43

Maybe I got it wrong, but I assume the only caller of the plugin methods is the letsencrypt core, so it should be guaranteed that it is called with the correct arguments, otherwise the core is violating the contract defined by itself, which seems odd. Also it does not seem so nice to require to write these checks in every plugin.

**Comment by coolaj86** [comment]
This is the reference implementation. The implementation tests the tests, the tests test the implementation. So no, you don't actually need to check.

**Comment by coolaj86** [comment]
The template that you actually pull from in the instructions does not have those checks:

https://github.com/Daplie/le-store-SPEC/blob/template/index.js
